# NumPy Refresher

In [1]:
import numpy as np
np.__version__

'1.18.1'

In [2]:
x = np.arange(10)
print(x)
type(x)

[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [3]:
y = np.arange(1_000_000)
y = y  ** 2

In [4]:
z = list(range(1_000_000))
z = z ** 2       # not possible, for loop required...

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

### Data Must be all the same type in numpy

In [5]:
animal = ['Dog', 45, dict(), tuple()]
animal

['Dog', 45, {}, ()]

In [6]:
np.array(animal)

array(['Dog', 45, {}, ()], dtype=object)

In [7]:
ndim = np.arange(27).reshape(3,3,3)
ndim

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [8]:
twos = np.arange(16).reshape(2,2,2,2)
twos

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [9]:
print(np.ones(1))

[1.]


In [10]:
%timeit np.random.normal(size=100)

5.33 µs ± 29.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Sometimes it is easier to define a data holder before actually generating the data

In [11]:
print(np.zeros((3,5)), end='\n\n')
print(np.ones((3,5)), end='\n\n')
print(np.eye(3,5), end='\n\n')
print(np.eye(5,5), end='\n\n')

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]



In [12]:
data = np.random.randint(10, size=15)
print(data)

[8 7 0 0 4 7 9 5 3 1 8 7 4 2 3]


In [13]:
data[0]

8

In [14]:
data[:3]

array([8, 7, 0])

In [15]:
data[2:5]

array([0, 0, 4])

In [16]:
data = data.reshape(3,5)
data

array([[8, 7, 0, 0, 4],
       [7, 9, 5, 3, 1],
       [8, 7, 4, 2, 3]])

In [17]:
data[0]     # first row

array([8, 7, 0, 0, 4])

In [18]:
data[:,0]   # First column

array([8, 7, 8])

In [19]:
data[0,3]   # first column, 3th index

0