In [1]:
import numpy as np

In [8]:
x = np.array([3,5,1,6,2,7])
print(x)
print(np.argsort(x))    # Array is unchanced, returns indices that would sort an array
print(x[x.argsort()])   # Array is unchanced, returns sorted array
print(x)

[3 5 1 6 2 7]
[2 4 0 1 3 5]
[1 2 3 5 6 7]
[3 5 1 6 2 7]


### You can use it to match up values from separate arrays

In [12]:
grade = np.array([3, 5, 1, 6, 2, 7])
ages = np.array([8, 10, 6, 11, 7, 12])
print(grade)
print(ages)

[3 5 1 6 2 7]
[ 8 10  6 11  7 12]


In [13]:
sort_index = np.argsort(ages)
sort_index

array([2, 4, 0, 1, 3, 5], dtype=int64)

In [14]:
print(grade[sort_index])
print(ages[sort_index])

[1 2 3 5 6 7]
[ 6  7  8 10 11 12]


### See the array as comma separated

In [17]:
print(grade[sort_index])
print(list(grade[sort_index]))

[1 2 3 5 6 7]
[1, 2, 3, 5, 6, 7]


### Indirectly sorting in descending order

In [18]:
ages[sort_index][::-1]

array([12, 11, 10,  8,  7,  6])